development:
  'https://dashboard.login.gov':
    acs_url: 'http://localhost:3001/users/auth/saml/callback'
    assertion_consumer_logout_service_url: 'http://localhost:3001/users/auth/saml/logout'
    sp_initiated_login_url: 'http://localhost:3001/users/auth/saml'
    block_encryption: 'aes256-cbc'
    cert: 'identity_dashboard_cert'
    attribute_bundle:
      - email
